In [1]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5

rand_tensor = torch.randn((3, 4, 5))
rand_tensor

tensor([[[ 1.4161,  0.8138,  0.5151,  0.8583,  0.6033],
         [-1.2834,  1.0560,  1.4298, -0.3610, -0.6701],
         [ 2.2825, -0.9691, -0.6821, -0.0910, -1.0592],
         [ 0.7938, -0.6766, -0.6855, -0.2699, -0.1856]],

        [[ 0.5758, -0.9846, -0.1412,  0.0743, -0.1331],
         [ 1.1045,  2.7017,  0.7415,  0.2941, -0.3186],
         [ 0.5598,  0.3069, -0.6652, -0.2786, -0.3763],
         [-0.8699,  0.0423, -0.9113,  1.1598, -1.1181]],

        [[ 0.5995,  0.3600,  0.3421,  0.4500, -0.4022],
         [ 0.3573,  0.9186,  0.5857, -2.5608, -0.0843],
         [-0.0636, -0.0394,  0.7251,  2.0815,  0.3415],
         [ 1.0498, -0.6210,  1.1402,  0.7392, -0.2321]]])

In [3]:
# Выведите его форму (shape)
rand_tensor.shape

torch.Size([3, 4, 5])

In [4]:
# Приведите его к форме 6 X 10
rand_tensor_mod = rand_tensor.reshape(6, 10)
rand_tensor_mod

tensor([[ 1.4161,  0.8138,  0.5151,  0.8583,  0.6033, -1.2834,  1.0560,  1.4298,
         -0.3610, -0.6701],
        [ 2.2825, -0.9691, -0.6821, -0.0910, -1.0592,  0.7938, -0.6766, -0.6855,
         -0.2699, -0.1856],
        [ 0.5758, -0.9846, -0.1412,  0.0743, -0.1331,  1.1045,  2.7017,  0.7415,
          0.2941, -0.3186],
        [ 0.5598,  0.3069, -0.6652, -0.2786, -0.3763, -0.8699,  0.0423, -0.9113,
          1.1598, -1.1181],
        [ 0.5995,  0.3600,  0.3421,  0.4500, -0.4022,  0.3573,  0.9186,  0.5857,
         -2.5608, -0.0843],
        [-0.0636, -0.0394,  0.7251,  2.0815,  0.3415,  1.0498, -0.6210,  1.1402,
          0.7392, -0.2321]])

In [5]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
a = torch.Tensor([1, 4, 2, 2, 1])

# Видимо имеется в виду умножить изначальный тензор с размерами (3, 4, 5) на заданный вектор?
# Или нужно размножить вектор a, чтобы он имел размерность (1, 10)?

rand_tensor * a

tensor([[[ 1.4161,  3.2551,  1.0302,  1.7167,  0.6033],
         [-1.2834,  4.2242,  2.8595, -0.7220, -0.6701],
         [ 2.2825, -3.8762, -1.3641, -0.1821, -1.0592],
         [ 0.7938, -2.7062, -1.3710, -0.5398, -0.1856]],

        [[ 0.5758, -3.9386, -0.2824,  0.1487, -0.1331],
         [ 1.1045, 10.8069,  1.4831,  0.5882, -0.3186],
         [ 0.5598,  1.2277, -1.3304, -0.5573, -0.3763],
         [-0.8699,  0.1693, -1.8226,  2.3195, -1.1181]],

        [[ 0.5995,  1.4399,  0.6842,  0.8999, -0.4022],
         [ 0.3573,  3.6744,  1.1714, -5.1217, -0.0843],
         [-0.0636, -0.1574,  1.4503,  4.1630,  0.3415],
         [ 1.0498, -2.4840,  2.2804,  1.4783, -0.2321]]])

In [6]:
rand_tensor_mod * a.repeat(int(rand_tensor_mod.shape[1] / a.shape[0]))

tensor([[ 1.4161,  3.2551,  1.0302,  1.7167,  0.6033, -1.2834,  4.2242,  2.8595,
         -0.7220, -0.6701],
        [ 2.2825, -3.8762, -1.3641, -0.1821, -1.0592,  0.7938, -2.7062, -1.3710,
         -0.5398, -0.1856],
        [ 0.5758, -3.9386, -0.2824,  0.1487, -0.1331,  1.1045, 10.8069,  1.4831,
          0.5882, -0.3186],
        [ 0.5598,  1.2277, -1.3304, -0.5573, -0.3763, -0.8699,  0.1693, -1.8226,
          2.3195, -1.1181],
        [ 0.5995,  1.4399,  0.6842,  0.8999, -0.4022,  0.3573,  3.6744,  1.1714,
         -5.1217, -0.0843],
        [-0.0636, -0.1574,  1.4503,  4.1630,  0.3415,  1.0498, -2.4840,  2.2804,
          1.4783, -0.2321]])

In [7]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

rand_tensor_mod @ rand_tensor_mod.T

tensor([[ 9.4197, -1.1164,  2.5281,  0.4223,  3.7917,  1.7598],
        [-1.1164,  9.4094,  1.0193,  1.6581,  1.1388, -0.8374],
        [ 2.5281,  1.0193, 10.6014, -0.6814,  2.6140,  0.6276],
        [ 0.4223,  1.6581, -0.6814,  5.2535, -3.4370, -2.1003],
        [ 3.7917,  1.1388,  2.6140, -3.4370,  8.8499, -0.4058],
        [ 1.7598, -0.8374,  0.6276, -2.1003, -0.4058,  8.3687]])

In [8]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

from torch.autograd import Variable

x = Variable(torch.Tensor([1]), requires_grad=True)
z = Variable(torch.Tensor([0.5]), requires_grad=True)
t = Variable(torch.Tensor([2]), requires_grad=True)

y = x**3 + z - 75 * t
y.backward()

print('dy/dx: ', x.grad) 
print('dy/dz: ', z.grad)
print('dy/dt: ', t.grad)

dy/dx:  tensor([3.])
dy/dz:  tensor([1.])
dy/dt:  tensor([-75.])


In [9]:
# Создайте единичный тензор размера 5x6
e = torch.ones((5, 6))
e

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [10]:
# Переведите его в формат numpy
e = e.numpy()
e

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [11]:
# возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

## Не понятно, что требуется в данном задании

extra *

https://www.tensorflow.org/tutorials/quickstart/beginner

In [12]:
torch.__version__

'1.10.0+cu102'

In [13]:
# !pip install ipywidgets
import torchvision
import torch.nn as nn

from torch.utils.data import DataLoader

In [14]:
train_dataset = torchvision.datasets.MNIST(
    root='files/train', train=True, download=True, transform=torchvision.transforms.ToTensor())

test_dataset = torchvision.datasets.MNIST(
    root='files/test', train=False, download=True, transform=torchvision.transforms.ToTensor())

In [15]:
# На основе класса модели и функций для обучения, предложенных в документации

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.model_layers = nn.Sequential(
            nn.Flatten(),
            nn.Linear(28*28, 128),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(128, 10)
        )

    def forward(self, x):
        logits = self.model_layers(x)
        return logits

model = Model()

In [16]:
def train_loop(dataloader, model, loss_fn, optimizer):
    model.train()
    size = len(dataloader.dataset)
    correct = 0

    for batch, (X, y) in enumerate(dataloader):
        # Compute prediction and loss
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 400 == 0:
            loss, current = loss.item(), batch * len(X)    
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")
        
        correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    correct /= size
    print(f'Train_ Accuracy: {(100*correct):>0.1f}%')

def test_eval(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, correct = 0, 0

    with torch.no_grad():
        for X, y in dataloader:
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [17]:
learning_rate = 1e-2
batch_size = 32
epochs = 5

train_dataloader = DataLoader(train_dataset, batch_size=batch_size)
test_dataloader = DataLoader(test_dataset, batch_size=batch_size)


loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train_loop(train_dataloader, model, loss_fn, optimizer)

test_eval(test_dataloader, model, loss_fn)

Epoch 1
-------------------------------
loss: 2.297778  [    0/60000]
loss: 0.284823  [12800/60000]
loss: 0.338857  [25600/60000]
loss: 0.160077  [38400/60000]
loss: 0.194211  [51200/60000]
Train_ Accuracy: 90.7%
Epoch 2
-------------------------------
loss: 0.171326  [    0/60000]
loss: 0.418745  [12800/60000]
loss: 0.111362  [25600/60000]
loss: 0.354188  [38400/60000]
loss: 0.202793  [51200/60000]
Train_ Accuracy: 92.9%
Epoch 3
-------------------------------
loss: 0.164735  [    0/60000]
loss: 0.306621  [12800/60000]
loss: 0.115215  [25600/60000]
loss: 0.272084  [38400/60000]
loss: 0.165195  [51200/60000]
Train_ Accuracy: 93.7%
Epoch 4
-------------------------------
loss: 0.037961  [    0/60000]
loss: 0.432489  [12800/60000]
loss: 0.314625  [25600/60000]
loss: 0.274421  [38400/60000]
loss: 0.190835  [51200/60000]
Train_ Accuracy: 94.2%
Epoch 5
-------------------------------
loss: 0.036200  [    0/60000]
loss: 0.250929  [12800/60000]
loss: 0.101584  [25600/60000]
loss: 0.297297  [3

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=547184c2-9c54-4234-82c9-4dd0d2e4822e' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>