In [122]:
import torch

In [123]:
print(f"Поддерживается ли CUDA : {torch.cuda.is_available()}")
print(f'Количество гпу девайсов: {torch.cuda.device_count()}')
print(f"Характеристики видеокарты : {torch.cuda.get_device_properties(0)}")

torch.cuda.empty_cache()

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

Поддерживается ли CUDA : True
Количество гпу девайсов: 1
Характеристики видеокарты : _CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15109MB, multi_processor_count=40)
cuda:0


In [124]:
# 1. Создайте случайный FloatTensor размера 3x4x5
a = torch.randn(size=(3, 4, 5)).type(torch.FloatTensor).to(device)
print(a.type())
a

torch.cuda.FloatTensor


tensor([[[ 0.0364, -1.1209, -0.3689, -0.6887,  0.5063],
         [-1.1245,  0.1863,  0.6880, -1.4812, -1.1475],
         [-0.4129, -0.0072, -0.6307, -0.2706,  0.3788],
         [-0.0654,  0.3361,  0.0322, -2.4554,  2.3167]],

        [[-0.1963,  0.5178,  0.1136,  1.1167,  1.5713],
         [ 0.2449, -1.2163,  0.1476, -0.3291,  0.2348],
         [-0.4144, -0.7224,  1.5283,  0.9703,  0.3563],
         [-0.1075, -1.3535, -0.1829, -0.4606,  1.4884]],

        [[-1.0873, -1.5436, -0.1006,  1.4502,  2.4190],
         [-0.3097,  0.7629, -2.2266,  0.9531,  1.9068],
         [ 1.8729,  0.8439, -1.8231, -0.0243, -0.2879],
         [-0.4226, -0.3595, -0.4590, -0.2964,  0.3137]]], device='cuda:0')

In [125]:
# 2. Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [126]:
# 3. Приведите его к форме 6х10

b = a.reshape(6, 10)
print(b.shape)
b

torch.Size([6, 10])


tensor([[ 0.0364, -1.1209, -0.3689, -0.6887,  0.5063, -1.1245,  0.1863,  0.6880,
         -1.4812, -1.1475],
        [-0.4129, -0.0072, -0.6307, -0.2706,  0.3788, -0.0654,  0.3361,  0.0322,
         -2.4554,  2.3167],
        [-0.1963,  0.5178,  0.1136,  1.1167,  1.5713,  0.2449, -1.2163,  0.1476,
         -0.3291,  0.2348],
        [-0.4144, -0.7224,  1.5283,  0.9703,  0.3563, -0.1075, -1.3535, -0.1829,
         -0.4606,  1.4884],
        [-1.0873, -1.5436, -0.1006,  1.4502,  2.4190, -0.3097,  0.7629, -2.2266,
          0.9531,  1.9068],
        [ 1.8729,  0.8439, -1.8231, -0.0243, -0.2879, -0.4226, -0.3595, -0.4590,
         -0.2964,  0.3137]], device='cuda:0')

In [127]:
# 4. Создайте случайный IntTensor размера 10

w = torch.randint(50, size=(10,)).type(torch.IntTensor).to(device)
print(w.type())
w

torch.cuda.IntTensor


tensor([25, 40, 30, 20, 17, 18, 34, 21, 25, 23], device='cuda:0',
       dtype=torch.int32)

In [128]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

b * w

tensor([[  0.9104, -44.8361, -11.0671, -13.7737,   8.6074, -20.2413,   6.3359,
          14.4488, -37.0288, -26.3917],
        [-10.3222,  -0.2895, -18.9204,  -5.4128,   6.4401,  -1.1765,  11.4290,
           0.6758, -61.3845,  53.2852],
        [ -4.9077,  20.7112,   3.4075,  22.3334,  26.7129,   4.4079, -41.3549,
           3.0987,  -8.2285,   5.4012],
        [-10.3597, -28.8958,  45.8495,  19.4067,   6.0579,  -1.9357, -46.0203,
          -3.8399, -11.5160,  34.2334],
        [-27.1837, -61.7453,  -3.0186,  29.0031,  41.1231,  -5.5750,  25.9401,
         -46.7577,  23.8278,  43.8559],
        [ 46.8231,  33.7569, -54.6922,  -0.4866,  -4.8944,  -7.6075, -12.2240,
          -9.6397,  -7.4100,   7.2147]], device='cuda:0')

In [129]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

b @ b.T

tensor([[ 7.4076,  1.7406, -0.7853, -1.5397, -2.6873, -0.1627],
        [ 1.7406, 12.2996,  1.2308,  3.2103,  3.3298,  1.6144],
        [-0.7853,  1.2308,  5.7603,  3.6186,  3.6249, -0.1801],
        [-1.5397,  3.2103,  3.6186,  8.4025,  5.4878, -3.0788],
        [-2.6873,  3.3298,  3.6249,  5.4878, 21.7096, -2.6932],
        [-0.1627,  1.6144, -0.1801, -3.0788, -2.6932,  8.3320]],
       device='cuda:0')

In [130]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x = torch.tensor([1.], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.], requires_grad=True)

y = x ** 3 + z - 75 * t
y.backward()

x.grad, z.grad, t.grad

(tensor([3.]), tensor([1.]), tensor([-75.]))

In [131]:
# 8. Создайте единичный тензор размера 5x6

e = torch.ones(size=(5, 6), device=device)
e

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], device='cuda:0')

In [132]:
# 9. Переведите его в формат numpy

e.to('cpu').numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)